### ISSUE TITLE
textInput value is undefined

### ISSUE THREAD

**Issue by niki-ito** [niki-ito/thesis-2022#5]
Hi @stalgiag.

I added a textInput slide in chapter 0 slide 2. I have a global variable called nameInput. In the textInput constructor, I createInput and assign the nameInput to this.input.value().

First issue is with my chapter0 text. I want to have the text's nameInput update once a value have been assigned but even after the name is submitted and there is value, the text shows "undefined" for the nameInput.
`this.slide3convoJ = [
            "私の名前は"+nameInput+"。ごく普通の中学生。", 
            "今日は夏休み明けで最初の学校。"];`

Second Issue is with the textInput.js. I have the elements hidden at the beginning and show when the slide is selected. I want to hide it again once the submit button is pressed but at that point, an error shows that this.input.hide() -which I used to hide the input at the beginning- is not a function anymore. I don't understand why this is happening.
`   this.hideElements();
    }

    display() {
        this.showElements();
        nameInput = this.input.value();
    
    }

    hideElements() {
        this.input.hide();
        this.instructions.hide();
        this.submitButton.hide();
    }

    showElements() {
        this.input.show();
        this.instructions.show();
        this.submitButton.show();
    }

    submitName() {
        this.hideElements();
        return true;
    }`

Thank you for your time.

**Comment by niki-ito** [comment]
Hi @stalgiag. The nameInput doesn't seem to work for the name plates. It doesn't show up if I just add `nameInput` in the array, and if I add `+nameInput` it shows up as NaN, and if I add some random word like `"h"+nameInput` it shows as hundefined. For the conversation, it works most of the time but not all. Would you be able to find what is wrong with it?

**Comment by stalgiag** [comment]
New pull request that will fix most of your problems. I forgot to replace on all messages. The NaN problem is because you aren't concatenating the string correctly and js is trying to interpret your '+' as a math equation. The 'hundefined' problem is because there is no space between h and nameInput so the hack-y fix that searches the strings for the word 'undefined' can't find the word 'undefined'. Try to be consistent with how you insert 'nameInput' into strings. I think[ template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) can be a nice way to write strings to avoid making common mistakes.
